mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/',include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from . import views
from django.urls import path

app_name = 'polls'

urlpatterns = [
    path("",views.index,name='index'),
    path("<int:question_id>/",views.details,name="details"),
    path("<int:question_id>/results/",views.results,name="results"),
    path("<int:question_id>/vote",views.vote,name="vote"),
]

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.

class Question(models.Model):
    question_text = models.TextField(max_length=100)
    pub_date = models.DateTimeField("date_published")

    def __str__(self):
        return self.question_text

    def was_this_published_recently(self):
        return (timezone.now() - datetime.timedelta(days=1)) >= self.pub_date <= timezone.now()

class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.TextField(max_length=2000)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from django.db.models import F
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.urls import reverse

from .models import Question,Choice


# Create your views here.

def index(request):
    question_list = Question.objects.order_by("-pub_date")[:5]
    context = {
        "question_list": question_list
    }
    return render(request,"polls/index.html",context)

def details(request,question_id):
    try:
        question = Question.objects.get(pk=question_id)
        context = {
            "question": question
        }
    except Question.DoesNotExist:
        raise Http404("Question doesn't exist")
    return render(request,"polls/details.html", context)

def results(request, question_id):
    question = get_object_or_404(Question,pk=question_id)
    return render(request,'polls/results.html', {"question":question})

def vote(request, question_id):
    question = get_object_or_404(Question,pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError,Choice.DoesNotExist):
        return render(
            request,"polls/details.html",
            {"question":question,"error_message":"You didn't select a choice"
             })
    else:
        selected_choice.votes=F("votes")+1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results",args=(question.id,)))

mysite/polls/templates/polls/details.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %} <p><strong>{{ error_message }}</strong></p> {% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
            <label for="choice{{ forloop.counter }}">{{choice.choice_text }}</label>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote"/>
</form>

mysite/polls/templates/polls/index.html
{% load static %}

{% if question_list %}
    <ul>
        {% for question in question_list %}
            <li><a href="{% url 'polls:details' question.id %}">{{ question.question_text}}</a> </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No Polls available</p>
{% endif %}

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote {{choice.votes|pluralize}}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:details' question.id%}">Vote Again!!</a>